### ISSUE TITLE
problem.py line 15 incorrect variable name reference

### ISSUE THREAD

**Issue by CodeSammich** [ezCGP/ezCGP#1]
Currently, the line is:

> problem.score_min

even though it is inside the `problem.py` file. This will cause a runtime error of 

> NameError: problem 'name' is not defined

Solution:

> Change line to score_min

**Comment by roddtalebi** [comment]
Changed line from
`problem.score_min = 1e-1`
to
`score_min = 1e-1`

https://github.com/ezCGP/ezCGP/blob/9040fca0c796e0a98f52e28b7f2eca70f36c4ed7/problem.py#L15

Good catch...of course I mess up 1 of the 2 lines I change after checking that everything works
