### ISSUE TITLE
cv2 Preprocessing Methods may only work on 1 channel not 3

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#102]
had issues with the thresholding...

might loop over all the channels and apply cv2 method or pick one at random?

**Comment by roddtalebi** [comment]
try just creating a fake numpy image -> ```img = np.random.random((256,256,3)*256```
and run one of the cv2 thresholding methods over the image. then try it again with only one layer ie img[:,:,0]

**Comment by roddtalebi** [comment]
so I realize now that I wasn't being patient and taking my time to think through the problem well enough...thresholding should only work on single channel images because the whole point is to set everything below the threshold to 0 and everything above to some 'max value'.

Maybe what we should do for these is convert the image to greyscale, apply the thresholding and append it as another layer? Or just not include any sort of thresholding?

Also I think it would be good to test each of the cv2 methods I wrote to make sure that they aren't missing any args. For example, I see now that the GaussianBlur should have a sigmaX and sigmaY.

Here are where the 'preprocessing' methods live:
https://github.com/ezCGP/ezCGP/blob/feature/%2398-get_running/codes/block_definitions/utilities/operators_Augmentor_preprocessing.py

**Comment by HemangRajvanshy** [comment]
Yeah, I agree. I think adding a 4th channel to image data might cause a lot of issues down the pipeline.

Do you have any ideas for how we might be able to test them?  Would it work to test only the methods with dummy variables and images independent of the rest of the pipeline?

**Comment by roddtalebi** [comment]
to reiterate what we discussed in our meeting today:

* to test that we are using the cv2 method: create a dummy image and apply the cv2 image. no error? did the image change at all?
* to test that our primitive with the cv2 method is working well: write in pdb.set_trace() calls before and after our cv2 method are called in the primitive to make sure the primitive is hitting those lines of code as expected
* to test that our primitive doesn't break the whole code base: remove the pdb statments and run the code like normal. doesn't break? good.

**Comment by roddtalebi** [comment]
we also discussed that we either want to check if the image has 1 or 3 channels, if 1 channel then we will apply cv2 thresholding, if not then we won't do anything to the image...so that will all happen in the primitive
OR
we will just loop over every channel/layer and apply the threshold to each
