### ISSUE TITLE
TensorFlow GPU

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#115]
verify that when we run on PACE-ICE that we are training with a GPU and not CPU
https://www.tensorflow.org/guide/gpu

Talk to Henry about getting his most recent pbs script

Note that our goal isn't to eventually go into training on multiple GPUs, but rather to use multiple gpus so that we can distribute the population over multiple gpus (instead of one gpu training 40 individuals; use 4 gpus each training 10 individuals; which is different from using  4 gpus to train one individual at a time)

**Comment by roddtalebi** [comment]
looks like our version of tensorflow should include both cpu and gpu usage

> For releases 1.15 and older, CPU and GPU packages are separate

https://www.tensorflow.org/install/gpu

**Comment by roddtalebi** [comment]
A good follow up (if you are too busy, this could be done in a second week of work), would be to create a brief wiki page for tensorflow...start by adding your notes, ie: "here is how to tell if tensorflow is using cpu or gpu and which gpu if multiple are available".

The reason I ask this is because I'm sure that this will be a frequent question with the code base as we get new students of varying experience and it could save some time in the future

**Comment by HemangRajvanshy** [comment]
edited the wiki: https://github.com/ezCGP/ezCGP/wiki/PACE-ICE

**Comment by roddtalebi** [comment]
Max's notes for getting gpu to work
https://vip.gatech.edu/wiki/index.php/Notebook_Maxim_Daniel_Geller#Utilizing_Tensorflow_on_PACE

My notes:
```
# open interactive session on node with gpu
conda install anaconda3/blahblah
# create conda env without tensorflow
conda load cuda/10.1
conda install https://anaconda.org/anaconda/cudnn/7.6.5/download/linux-64/cudnn-7.6.5-cuda10.1_0.tar.bz2
pip install tensorflow-gpu==2.2.0
```

**Comment by roddtalebi** [comment]
with these learnings, going to try and redo the way we make conda environments...remove tensorflow and mpi4py and have everyone use pip
