### ISSUE TITLE
Other SimGAN Objectives?

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#219]
We want to be in multi-objective space but what other objectives can we or should we use?

- feature distance
- difference of AUC
- FID score
- support size

**Comment by roddtalebi** [comment]
NOTE! Only 1 objective function currently used...refiner ranking/score
https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/problems/problem_simgan.py#L127

**Comment by roddtalebi** [comment]
@gabriel-q-wang Can you send over your powerpoint/slidedeck for me to look at. also can you think of some really quick objectives we can add to the optimization?
We only have 2 objectives right now, one of which is the refiner rating which is a 'relative' score so it is hard to compare fitness values of individuals across different generations ie we can't do auc plots over time

**Comment by roddtalebi** [comment]
Dude, excellent. And, at first glance, you slid the code in the right parts.

**Comment by roddtalebi** [comment]
Going to keep this Issue open so that we can do the following next:

- Keep tracking refiner ratings
- BUT do not use it for population selection and hall of fame criteria etc

Then verify with Jason that we are implementing as he expects (where to use refiner-rating and where not to)

**Comment by roddtalebi** [comment]
for now, just found it easier to not attach refiner rating to fitness.values at all but rather make a new attribute to the individual material class.
only place this may be problematic is in seeding an individual from a pkl file (new unexpected attribute when compared to individual material class), but i don't think so

testing code and will close issue if successful

**Comment by gabriel-q-wang** [comment]
Oh that reminds me that I was looking through individual_evaluate.py and found that evaluate() only returns the "best" refiner and discriminator based on the tournament evaluation. Did we want to change that for multi-objective stuff?
https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/codes/individual_definitions/individual_evaluate.py

**Comment by roddtalebi** [comment]
i think it's fine but can you make a note to bring it up with jason at our next meeting?

**Comment by roddtalebi** [comment]
this stuff takes foreverrrrr

**Comment by gabriel-q-wang** [comment]
Yeah I'm considering not including the support size metric or using a subset of the synthetic data to run it, since I think that's taking up ages. That or it's a different error that causing it to hang? I might do more testing on that, since I might have preemptively pushed without thinking of scale.

**Comment by roddtalebi** [comment]
also relevant here...which objectives we are going to pick from the long list we added
https://github.com/ezCGP/ezCGP/issues/225#issuecomment-1082017918

**Comment by roddtalebi** [comment]
@gabriel-q-wang I took out the .T in this line. I think we want the dict keys to be the columns names
https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/codes/utilities/simgan_feature_eval.py#L51

**Comment by gabriel-q-wang** [comment]
Oh yeah that's right and fixes the bug. I can push a fix real quick, and comment out the support size metric since that takes a long time to calculate and we're not using it right now.

**Comment by roddtalebi** [comment]
no big deal. i made the change in the repo anish and i are working on so it'll get merged in soon enough anyways
