### ISSUE TITLE
Implement FID

### ISSUE THREAD

**Issue by anishthite** [ezCGP/ezCGP#232]

**Comment by anishthite** [comment]
I forgot I needed an eval function to test. @roddtalebi  where should I add this?

**Comment by roddtalebi** [comment]
@anishthite let me push up some code real quick + merge. fixed random bugs. but it'll be in Problem.objective_function()
https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/problems/problem_simgan.py#L102

**Comment by roddtalebi** [comment]
@anishthite successfully merged in 
https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/problems/problem_simgan.py#L92

Add any additional objectives to the tuple of the individuals .fitness.values attribute.

And if we are maximizing the FID score then add a -np.inf to this tuple...else do a np.inf  https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/problems/problem_simgan.py#L103

**Comment by roddtalebi** [comment]
i've been running the code i just pushed/merged and it has cleanly gone through 3 generations...trying to see if it'll cleanly finish all 5
