### ISSUE TITLE
Plot Pareto Fronts

### ISSUE THREAD

**Issue by anishthite** [ezCGP/ezCGP#238]
It doesn't seeem like we are plotting the outputs, is there a reason for that? I want to plot_things so that I can see if FID is working

**Comment by roddtalebi** [comment]
nope just didn't want to worry about that stuff just yet. hopefully [this](https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/post_process/plot_things.py) works 'out of the box'. grep to see which problem files use the plot_pareto_front() and see how it used

**Comment by roddtalebi** [comment]
Now that we changed how we set the objective scores to min/max, I should look into how we can updated the plotting code to accept/look for these new features to help it decide how to plot the objectives or change the scores to make plotting easier. ...try to reduce how much the user has to pass in arguments

**Comment by roddtalebi** [comment]
The other thing that Jason mentioned is that he wants Pareto Front and AUC as a graph over time...it is preferred to use halloffame for any 'over time' plots but then have the option to use the population at the end of a generation (before doing pop selection for next generation) for any plots about a single generation.

**Comment by roddtalebi** [comment]
pushed up code in this commit 
https://github.com/ezCGP/ezCGP/commit/9026a3ddf909c1eba4db19b1de5fe87722a099e2
in this branch
https://github.com/ezCGP/ezCGP/tree/feature/simgan_support/Issue245_PostProcess

@anishthite 
I put in a little block to help myself with making sure the pareto stuff and auc stuff is happening correctly. from now on, auc will always be calculated relative to the population rather that with setting borders to 0. check out the test code in postprocess_generation method...you can't miss it

review my code for plotting pareto...one for the hall of fame at that generation, the other for best pareto front over each generation.
also put in code to get you started with plotting auc over time

also eventually decided on adding this chunk of code to help toggle between testing and not testing
https://github.com/ezCGP/ezCGP/blob/feature/simgan_support/Issue245_PostProcess/codes/individual_definitions/individual_evaluate.py#L385
I'll update the other issue/pr where i mentioned this

**Comment by roddtalebi** [comment]
going to delete this part of the code so gonna copy/paste here for quick reference

```
        #################################################################################
        #################################################################################
        # TEST AREA
        # make some fake fitness scores
        data0 = [[0.25, 0.6], #<-pareto
                [0.75, 0.2], #<-pareto
                [0.50, 0.4], #<-pareto
                [0.20, 0.2], #<-should become left border for AUC calc
                [0.60, 0.1], #<-should become right border for AUC calc
                [0.30, 0.3]] 
        data0 = np.array(data0)
        pareto_fronts0 = plot_things.get_pareto_front(data0,
                                                      [True, True], # <- maximizing both objectives
                                                      x_objective_index=0,
                                                      y_objective_index=1,
                                                      first_front_only=True)

        print("Verify Pareto Front individuals in test case")
        front = pareto_fronts0[0] # remember, it returns a list of lists but first_front_only is True so there is only 1 element
        for indiv in front:
            # NOTE: it'll get sorted in the plot_pareto_front2() method
            print(indiv.fitness.wvalues)

        test_fig, test_axis = plot_things.plot_init(nrow=1, ncol=1, figsize=None, xlim=None, ylim=None)
        plot_things.plot_pareto_front2(test_axis[0,0],
                                       pareto_fronts0,
                                       color=None, label="HOF Gen %i" % (universe.generation),
                                       x_objective_index=0, y_objective_index=1,
                                       xlabel='bogus 0', ylabel='bogus 1',
                                       min_x=None, max_x=None,
                                       min_y=None, max_y=None)

        import matplotlib.pyplot as plt
        plt.show()
        plt.close()

        # calc auc
        auc0 = plot_things.calc_auc([True, True],data0) # <-note we give it all data, not just the front

        # but now what if we have multiple generations?
        # make more fitness scores as if a second generation calculated
        data1 = np.random.random((10,2))
        pareto_fronts1 = plot_things.get_pareto_front(data1,
                                                      [True, True], # <- maximizing both objectives
                                                      x_objective_index=0,
                                                      y_objective_index=1,
                                                      first_front_only=True)

        all_auc = plot_things.calc_auc_multi_gen([True, True], data0, data1) # <-again give it all the data not just the front

        print("check test auc stuff"); import pdb; pdb.set_trace()
        #################################################################################
        #################################################################################
```
