### ISSUE TITLE
Why do Pareto + AUC plots 'bounce' around

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#241]
If we are doing elitism right, then the plots should always improve over time

**Comment by roddtalebi** [comment]
@anishthite 
 I FIGURED IT OUT ON ACCIDENT

The first objective is 'refiner rating' which is a score relative to the current population...there are a series of matches/tournaments between all the refiners in the population and a rating is produced from that. So that fitness score in particular is going to change from generation to generation even if it is the score for the same individual from generation to generation!

@jasonzutty does this make sense? what should we do about it? just accept that our plot is going to bounce when looking at change over generations?

**Comment by anishthite** [comment]
If we let it bounce around wouldn't that mess up the evolution? For example,if we are comparing two different individuals to see who dominates its possible one of them may have had an easier set of discriminators to compete against. This would make the score inflated, messing up the pareto front.

Maybe what we can do is include a hall of fame of discriminators in the tournament each time,(eg. keep the top 10 Ds) so there is some commonality between gens

**Comment by roddtalebi** [comment]
I say let's add a 3rd objective score and make pareto plots with fid and the 3rd score.
Regardless, we should check in with Jason on this on Tuesday; so hold off until then I guess

**Comment by roddtalebi** [comment]
clarified by jason and we added other objectives
