### ISSUE TITLE
output architecture + sample refined signals

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#245]
As part of a regular 'postprocessing' for every generation, have scripts to visualize the architecture (should exist from last year's vip group) and output sample refined signals to get an idea of what they can do.

**Comment by anishthite** [comment]
Where is the script for visualizing the architecture? I can test if outputting the sample refined signals works

**Comment by roddtalebi** [comment]
I found the visualizing code; it needs a lot of overhauling and improving. I'll have it done tomorrow hopefully

**Comment by roddtalebi** [comment]
Check out recent commits mentioned above. Added code to visualize architecture. Still need to add code to visualize refined signal

**Comment by roddtalebi** [comment]
@anishthite @gabriel-q-wang 
Do we have some code that we can add to handle the visualization? I can put in the code myself to make the calls in postprocess_generation but if one of you guys can just make a script in codes/utilities or misc/ and copy + paste the code from your other repo...basically just a huge starting point

**Comment by gabriel-q-wang** [comment]
Sorry, yeah I can get on it real quick

**Comment by gabriel-q-wang** [comment]
Forgot to commit the signal changes, just pushed up now. Right now it picks the first 5 signals in both the real and simulated datasets and it uses the same 5 examples for all visualizations. Not sure if we wanted to change it so we could see a wider variety of other signals.
