### ISSUE TITLE
Speed up Evaluation/Training

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#247]
Is there anything that can be changed to improve evaluation/training times? what are our benchmarks?

**Comment by anishthite** [comment]
I'm not sure of benchmarks for this. I looked through https://arxiv.org/pdf/1803.00657.pdf but couldn't find anything helpful for matching training times. I'll look more at other NAS papers to see what is accessible. It also heavily depends on the dataset, so our expected training times are going to differ from people training on CIFAR, which is what a lot of the papers use

Some things that we can change:
- using more nodes on Icehammer
- using multiple evaluation processes (I couldn't tell if there were multiple processes going on a single node)
- Are we actually using the GPU? At least for the post-processing everything is done on the CPU. We could at least convert that to GPU but that might not have many gains
- Weight sharing between models might work. I think there was a VIP team looking at this so ill look at what they are doing with EMADE more
- fp16 tensors - would give us more minibatches per model, also could squeeze more processes in a node

I'll add more if I think of any

**Comment by anishthite** [comment]
Also noticed that we don't use multiple GPUs:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:03:00.0 Off |                    0 |
| N/A   39C    P0    46W / 250W |   6260MiB / 32510MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:84:00.0 Off |                    0 |
| N/A   23C    P0    25W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      8006      C   python                           6093MiB |
|    0   N/A  N/A      8104      G   /usr/bin/X                         63MiB |
|    0   N/A  N/A      8226      G   /usr/bin/gnome-shell               98MiB |
|    1   N/A  N/A      8104      G   /usr/bin/X                          0MiB |
|    1   N/A  N/A      8226      G   /usr/bin/gnome-shell                0MiB |
+-----------------------------------------------------------------------------+
```

**Comment by roddtalebi** [comment]
@anishthite good catch; you have bandwidth to look into it?
https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html
https://pytorch.org/tutorials/intermediate/ddp_tutorial.html

I can try tomorrow if you don't have time today

**Comment by roddtalebi** [comment]
About to push up some code to print which gpu we are using...hopefully it'll eventually work for multiple gpus buuuut i doubt it'll work clean no changes
```
        # Adding GPU meta data info
        if torch.cuda.is_available():
            #gpu_device = torch.cuda.current_device()
            for gpu_device in range(torch.cuda.device_count()):
                gpu_name = torch.cuda.get_device_name(gpu_device)
                if gpu_name is not None:
                    ezLogging.debug("%s - Using GPU #%i: %s" % (indiv_material.id, gpu_device, gpu_name))
```

**Comment by roddtalebi** [comment]
Def can speed up the tournament selection/ranking by changing the 'save_every' value
https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/codes/individual_definitions/individual_evaluate.py#L520

If we train for 5,000 steps, save for every 100? ...that would give 50 refiners/discriminators to choose from...too many?

**Comment by anishthite** [comment]
we can save every 1000, from my experience there's not too much variation every 100 epochs. I'll double check though with a few experiments.

**Comment by roddtalebi** [comment]
I'll change it to every 1000 then.
I talked to Jason today and he said that we don't need to worry about mutliple gpus at the moment...good to document for future but since we have mpi to run on multiple computers, we'll just assign 1 gpu to each 'computer'
