### ISSUE TITLE
Verify genome seed arguments for Train Config

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#250]
I just found a 'todo' here and it is important!
[These are the argument values](https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/misc/seed_simgan.py#L194) that correspond to the expected arguments [set here](https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/codes/block_definitions/utilities/operators_simgan_train_config.py#L26)

Can one of you guys verify or edit the values that should be there? Be sure that if you make a change, that the change also exists as a 'valid choice' in the [argument types file for that corresponding arg type](https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/codes/block_definitions/utilities/argument_types.py)

**Comment by anishthite** [comment]
I double checked with the stuff in simgan, the only other thing we have is an optimizer variable switching between adam and rmsprop with adam being the default.

**Comment by roddtalebi** [comment]
@anishthite 
so basically would replace [this line](https://github.com/ezCGP/ezCGP/blob/feature/simgan-support/codes/individual_definitions/individual_evaluate.py#L396) with rmsprop instead?

If we wanted to add the rmsprop option, what would it that line above look like instead?
