### ISSUE TITLE
Research Data Augmentation

### ISSUE THREAD

**Issue by Michaeljurado24** [ezCGP/ezCGP#26]
Before fixing data augmentation in ezcgp it is neccessary to research data augmentation and find a framework (pytorch, keras, custom method) for data augmentation.

**Comment by roddtalebi** [comment]
![IMG_20200118_131104](https://user-images.githubusercontent.com/7659765/73124943-361cd380-3f6f-11ea-88a6-8fd0bc2787d8.jpg)
![IMG_20200118_131054](https://user-images.githubusercontent.com/7659765/73124944-361cd380-3f6f-11ea-8ecf-21f93188f6ef.jpg)

**Comment by roddtalebi** [comment]
^ strategy we want to implement for next week

**Comment by roddtalebi** [comment]
Links provided as a start by @Michaeljurado24 
https://machinelearningmastery.com/how-to-configure-image-data-augmentation-when-training-deep-learning-neural-networks/

https://www.geeksforgeeks.org/python-data-augmentation/

**Comment by Michaeljurado24** [comment]
The Links that @roddtalebi posted show keras augmentation. Here is a link for pytorch Augmentation: https://pytorch.org/docs/stable/torchvision/transforms.html

**Comment by Michaeljurado24** [comment]
A couple disadvantages about keras augmentation:
1) There is no way to add more primitives
2) There is an ordering to the data augmentation primitives, but it is imposed. (See apply_transform functin in https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/image_data_generator.py)

Here is another augmentation framework we can use which was featured in the geeksforgeeks link: https://augmentor.readthedocs.io/en/master/

I believe that Pytorch and Augmentor are more flexible data-augmentators with lots of room for feature expansion. On the other hand, Keras is probably more convenient (as usual).

**Comment by WilliamYuhangLee** [comment]
I have been reading [Augmentor](https://github.com/mdbloice/Augmentor)'s documentation and were able to produce an example [script](https://github.com/WilliamYuhangLee/AAD/blob/master/TeamEzcgp/ResearchAugmentor/augmentor_exercise.py) for using it.
Its usage is pretty intuitive, declaring a pipeline with operators and sample from it. The best of all, it can be easily integrated with Keras and Pytorch:
```
transforms = torchvision.transforms.Compose([
    p.torch_transform(),
    torchvision.transforms.ToTensor(),
])

**Comment by Michaeljurado24** [comment]
I'm closing this because we are officially using Augmentor in our preprocessing block!
