### ISSUE TITLE
Come up with Data Augmentation Fix/Plan 

### ISSUE THREAD

**Issue by Michaeljurado24** [ezCGP/ezCGP#27]

**Comment by roddtalebi** [comment]
![IMG_20200118_131104](https://user-images.githubusercontent.com/7659765/73124961-6a908f80-3f6f-11ea-805b-ed1a7ebcb8f6.jpg)
![IMG_20200118_131054](https://user-images.githubusercontent.com/7659765/73124962-6a908f80-3f6f-11ea-8c69-2631ae5f5cd1.jpg)

^ the strategy we want to implement

**Comment by Michaeljurado24** [comment]
I like it

**Comment by bojunyang24** [comment]
We are going to use augmenter python library instead
