### ISSUE TITLE
summary write up of data used

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#276]
Just to tie the bow on everything, can you drop links to box (the whole universe0000 folder ideally) and specify any relevant individuals you looked at for the paper.
no rush on this but ideally before we forget. just want it captured somewhere for the record.

also, i remembered that i put a line in the logging to record which commit of the code we are using...very hot https://github.com/ezCGP/ezCGP/blob/master/codes/utilities/custom_logging.py#L112

**Comment by anishthite** [comment]
All the data can be found at https://gtri.box.com/s/mu2opltlr883ma8hkekh01nmwb67vsxu 

We ended up using run 20220409-190119 as the run for the paper (purely since it ran the longest)

Seed individual used: gen_0000_indiv_seededIndiv0-1
Evolved individual used: gen_0009_indiv_2d311ddb156f0
