### ISSUE TITLE
[GPU] Integrate Horovod with ezCGP MPI

### ISSUE THREAD

**Issue by maipham** [ezCGP/ezCGP#29]

**Comment by traitran44** [comment]
What steps need to be taken to integrate?

**Comment by traitran44** [comment]
Able to get Horovod running with ezCGP

**Comment by maipham** [comment]
Installed openmpi on gcloud successfully, now waiting to get some info about the os image the instance is running on, once confirm, will install cudatoolkit

**Comment by maipham** [comment]
Team has decided to not use Horovod because of dependencies incompatibility
