### ISSUE TITLE
Mutation method type checking

### ISSUE THREAD

**Issue by AniruddhaDas1998** [ezCGP/ezCGP#4]
Mutate_methods.mutate_singleFtn 
current: check that the input datatypes match, however, output datatypes don't necessarily match.

**Comment by roddtalebi** [comment]
singleFtn used randomFtn which didn't have an option to return a random function that matches a certain datatype. ...added that functionality to randomFtn and got singleFtn to work with it
https://github.com/ezCGP/ezCGP/commit/a1562f6f4aa078229204955c4879b5b8e604ae2f
