### ISSUE TITLE
Add subtraction primitive to Operators.py

### ISSUE THREAD

**Issue by Michaeljurado24** [ezCGP/ezCGP#41]
Currently we only have a sum_func in Operators.py

**Comment by tantan13** [comment]
Added subtraction primitive to Operators.py which basically takes two tensors, turns one into a zero vector image and then it subtracts the zero parts from the image and then it subtracts it from the original image. At the moment this only works for Conv layer testing so at the moment it only works with 2d input, and I'll be working on making it work with Dense layer aka 1d input.

**Comment by Michaeljurado24** [comment]
Great!
