### ISSUE TITLE
Redesign and Implement Data Objects (DataSet, DbManager)

### ISSUE THREAD

**Issue by traitran44** [ezCGP/ezCGP#52]

**Comment by WilliamYuhangLee** [comment]
Commit and branch made for incorporating new Dataset class into ezExperimental: [Add Dataset class, incorporated Augmentor](https://github.com/ezCGP/ezExperimental/commit/02795d32a6fc4f05f2eba487ec34b3e405dd1a92)
Pending pull request: https://github.com/ezCGP/ezExperimental/pull/1
