### ISSUE TITLE
Visualize ezCGP Objects Dependency in drawing or graph

### ISSUE THREAD

**Issue by traitran44** [ezCGP/ezCGP#53]

**Comment by maipham** [comment]
![image](https://user-images.githubusercontent.com/34165109/75005895-e7fbd280-543d-11ea-89b5-34b83af33ab8.png)

**Comment by maipham** [comment]
Link for anyone to edit:
https://drive.google.com/file/d/1xdu5ZFESurDWoRQ3u9JnJxfaXs-BWKEi/view?usp=sharing
