### ISSUE TITLE
Fix module imports in operators.py

### ISSUE THREAD

**Issue by Michaeljurado24** [ezCGP/ezCGP#62]
The weight dict in SymbRegressionNoArgs contains references to simple_numpy.py. The only reference to simple numpy should be in the modules variable, which is used to update the self.operator_dict. 

Possible fixes include adding a "weight" key to each function in simple_numpy.py.

Also, we should refactor utils.build_weights
We can make a pull request after the presentation.

**Comment by HemangRajvanshy** [comment]
No more `operators.py`
