### ISSUE TITLE
Dense/Fully Connected Layer

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#73]
Pretty basic...add option for a Dense layer. One thing we have to think about is whether we want to add an option to 'flatten' the data before we pass it into the connected layer...have that as an arguement flag to flatten or not? always flatten if the data doesn't look 'flat'?

**Comment by Daniel-Martin576** [comment]
@roddtalebi, I am kinda confused about what you want from this issue. Why wouldn't we always want to flatten before the dense layer as a sanity check?

**Comment by HemangRajvanshy** [comment]
What is happening with this issue?

**Comment by roddtalebi** [comment]
Right now our evolution only chooses constitutional layers. Before finishing the graph we always flatten and add a single dense layer
https://github.com/ezCGP/ezCGP/blob/feature/PACE-runs/codes/block_definitions/block_evaluate.py#L691

I thought of keeping this open just to have something to think about when it comes to improving that part of the graph. Like VGG16's network ends in 3 fully connected layers and not one. is that something we should evolve?

**Comment by roddtalebi** [comment]
I don't know. maybe this issue should be closed and another issue put in to "rethink how we flatten + finish our CNNs".
