### ISSUE TITLE
Misc Keras Primitives

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#74]
- Concatenate
- Average maybe?
- anything else from the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers)?

**Comment by HemangRajvanshy** [comment]
I think the most useful layers would be:
- GaussianNoise (https://www.tensorflow.org/api_docs/python/tf/keras/layers/GaussianNoise)
- MaxPool2D (https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPool2D)
- AveragePooling2D (https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling2D)

These are just some of the layers I have seen most commonly in CNNs. Thoughts?

**Comment by roddtalebi** [comment]
ya sounds good to me

**Comment by roddtalebi** [comment]
@HemangRajvanshy and if you come across more as you finish this issue, just add a comment to the issue... "maybe later on we would want to look into blah blah blah", that way even when the issue closes, we have notes on what we could later do (of course assuming we are astute enough to look through our issues in the future)

**Comment by Daniel-Martin576** [comment]
Might be wrong, but it looks like MaxPool2D and AveragePooling2D are already implemented [here](https://github.com/ezCGP/ezCGP/blob/81f8d07432511b6cf73a2d7d192b67f239af1df4/codes/block_definitions/utilities/operators_TensorFlow_pooling.py#L41).
Avg Pooling was using Max so I updated it and added Gaussian noise primitive to feat/74-misc-primitive-pooling

**Comment by roddtalebi** [comment]
NOTE: I'm going to keep this issue open. I think I'm going to try and move the code that Daniel finished out of the 'pooling' script into a single 'keras' script and delete the other scripts...just a note for myself to do
